=== David-Job/E2_UF2217_David_Job/registroPersonal.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.ejemplo.com"
    xmlns="https://www.ejemplo.com"
    elementFormDefault="qualified">

    <!-- Definición de tipos -->

    <xs:simpleType name="Email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9\-._]+\@[a-z]+\.[a-z]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Telefono">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NombrePropio">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-ZÁ-Ú][a-zá-ú]+( [A-ZÁ-Ú][a-zá-ú]+)*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="LetraSexo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="V" />
            <xs:enumeration value="H" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Contacto">
        <xs:sequence>
            <xs:element name="email" type="Email" />
            <xs:element name="telefono" type="Telefono" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Direccion">
        <xs:sequence>
            <xs:element name="calle" type="xs:string" />
            <xs:element name="ciudad" type="xs:string" />
            <xs:element name="codigoPostal" type="xs:integer" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Contratado">
        <xs:sequence>
            <xs:element name="nombre" type="NombrePropio" />
            <xs:element name="sexo" type="LetraSexo" />
            <xs:element name="contacto" type="Contacto" />
            <xs:element name="departamento" type="RefDepartamento" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="IdEmpleado">
        <xs:restriction base="xs:ID">
            <xs:pattern value="E\d{3}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IdConsultor">
        <xs:restriction base="xs:ID">
            <xs:pattern value="C\d{3}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IdDepartamento">
        <xs:restriction base="xs:ID">
            <xs:pattern value="D\d{3}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RefDepartamento">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="D\d{3}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RefsContratados">
        <xs:restriction base="xs:IDREFS">
            <xs:pattern value="[EC]\d{3}(\s[EC]\d{3})*" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Elemento Raíz -->

    <xs:element name="registroPersonal">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="empleado" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="Contratado">
                                            <xs:attribute name="codigo" type="IdEmpleado" />
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="consultores">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="consultor" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="Contratado">
                                            <xs:sequence>
                                                <xs:element name="empresaExterna" type="xs:string" />
                                            </xs:sequence>
                                            <xs:attribute name="codigo" type="IdConsultor" />
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="director" type="NombrePropio" />
                                        <xs:element name="empleados" type="RefsContratados" />
                                        <xs:element name="direccion" type="Direccion" />
                                    </xs:sequence>
                                    <xs:attribute name="codigo" type="IdDepartamento"
                                        use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== David-Job/E2_UF2217_David_Job/registroPersonal.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="vistas/registroPersonal.xsl" type="text/xsl"?>
<registroPersonal
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="validadores/registroPersonal.xsd">

    <empleados>
        <empleado codigo="E001">
            <nombre>Pancho Rodríguez</nombre>
            <sexo>V</sexo>
            <contacto>
                <email>prod@yahoo.com</email>
                <telefono>768506530</telefono>
            </contacto>
            <departamento codigo="D001" />
        </empleado>

        <empleado codigo="E002">
            <nombre>Rafe Ortiz</nombre>
            <sexo>V</sexo>
            <contacto>
                <email>rortiz@gmail.com</email>
                <telefono>797605910</telefono>
            </contacto>
            <departamento codigo="D002" />
        </empleado>

        <empleado codigo="E003">
            <nombre>Nereida Candella</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>necan@outlook.com</email>
                <telefono>624305240</telefono>
            </contacto>
            <departamento codigo="D003" />
        </empleado>

        <empleado codigo="E004">
            <nombre>Antonina Fernandez</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>af@gmail.com</email>
                <telefono>848281695</telefono>
            </contacto>
            <departamento codigo="D004" />
        </empleado>

        <empleado codigo="E005">
            <nombre>Nelio Castejón</nombre>
            <sexo>V</sexo>
            <contacto>
                <email>nelioc@aol.com</email>
                <telefono>744279892</telefono>
            </contacto>
            <departamento codigo="D001" />
        </empleado>

        <empleado codigo="E006">
            <nombre>Lula Salinas</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>lsal@yandex.com</email>
                <telefono>773034987</telefono>
            </contacto>
            <departamento codigo="D002" />
        </empleado>

        <empleado codigo="E007">
            <nombre>Concetta Gutiérrez</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>cgut@protonmail.com</email>
                <telefono>801667731</telefono>
            </contacto>
            <departamento codigo="D003" />
        </empleado>

        <empleado codigo="E008">
            <nombre>Rosendo Aguilar</nombre>
            <sexo>V</sexo>
            <contacto>
                <email>rag@hotmail.com</email>
                <telefono>720216041</telefono>
            </contacto>
            <departamento codigo="D004" />
        </empleado>

        <empleado codigo="E009">
            <nombre>Lonzo Escarra</nombre>
            <sexo>V</sexo>
            <contacto>
                <email>lescarra@tuta.com</email>
                <telefono>667533346</telefono>
            </contacto>
            <departamento codigo="D001" />
        </empleado>

        <empleado codigo="E010">
            <nombre>Briand González</nombre>
            <sexo>V</sexo>
            <contacto>
                <email>briandg@live.com</email>
                <telefono>607366967</telefono>
            </contacto>
            <departamento codigo="D002" />
        </empleado>
    </empleados>


    <consultores>
        <consultor codigo="C001">
            <nombre>Nemesio Rodríguez</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>nemesi5@aol.com</email>
                <telefono>635008474</telefono>
            </contacto>
            <departamento codigo="D001" />
            <empresaExterna>Quaerat</empresaExterna>
        </consultor>

        <consultor codigo="C002">
            <nombre>Alba Betancourt</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>alba_beta@protonmail.com</email>
                <telefono>856252931</telefono>
            </contacto>
            <departamento codigo="D002" />
            <empresaExterna>Possimus</empresaExterna>
        </consultor>

        <consultor codigo="C003">
            <nombre>Segundo Vargas</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>2vargas@yandex.com</email>
                <telefono>664527044</telefono>
            </contacto>
            <departamento codigo="D003" />
            <empresaExterna>Earum</empresaExterna>
        </consultor>

        <consultor codigo="C004">
            <nombre>Donatello Gómez</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>ninja_gomez@aol.com</email>
                <telefono>600888157</telefono>
            </contacto>
            <departamento codigo="D004" />
            <empresaExterna>Commodi</empresaExterna>
        </consultor>

        <consultor codigo="C005">
            <nombre>Ramona Alonso</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>laramona@yahoo.com</email>
                <telefono>842359077</telefono>
            </contacto>
            <departamento codigo="D001" />
            <empresaExterna>Voluptates</empresaExterna>
        </consultor>

        <consultor codigo="C006">
            <nombre>Maximiliano Escarra</nombre>
            <sexo>H</sexo>
            <contacto>
                <email>maxescarra@outlook.com</email>
                <telefono>874430559</telefono>
            </contacto>
            <departamento codigo="D002" />
            <empresaExterna>Vero</empresaExterna>
        </consultor>
    </consultores>


    <departamentos>
        <departamento codigo="D001">
            <nombre>Finanzas</nombre>
            <director>Marisa Tamayo</director>
            <direccion>
                <calle>Colonia Inés Ulibarri</calle>
                <ciudad>La Mesa</ciudad>
                <codigoPostal>82238</codigoPostal>
            </direccion>
        </departamento>

        <departamento codigo="D002">
            <nombre>Ventas</nombre>
            <director>Amador Sanchez</director>
            <direccion>
                <calle>Salida Luis</calle>
                <ciudad>Tuscaloosa</ciudad>
                <codigoPostal>71071</codigoPostal>
            </direccion>
        </departamento>

        <departamento codigo="D003">
            <nombre>Recursos Humanos</nombre>
            <director>Lucilla Padron</director>
            <direccion>
                <calle>Muelle Claudio Tapia</calle>
                <ciudad>San Diego</ciudad>
                <codigoPostal>17348</codigoPostal>
            </direccion>
        </departamento>

        <departamento codigo="D004">
            <nombre>Investigacion y Desarrollo</nombre>
            <director>Manuel Monedero</director>
            <direccion>
                <calle>Extrarradio Gloria Palomino</calle>
                <ciudad>Esterlinas</ciudad>
                <codigoPostal>30559</codigoPostal>
            </direccion>
        </departamento>
    </departamentos>
</registroPersonal>
